#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

declare -A OS_ARCH_ARG

OS_PLATFORM_ARG=(linux windows)
OS_ARCH_ARG[linux]="amd64"
OS_ARCH_ARG[windows]="amd64"

if [ -n "$CROSS" ]; then
    rm -rf bin/*
    mkdir -p bin
    for OS in ${OS_PLATFORM_ARG[@]}; do
        for ARCH in ${OS_ARCH_ARG[${OS}]}; do
            OUTPUT_BIN="bin/$OS/$ARCH/rancher-dns"
            LINKFLAGS=" -extldflags -static"
            if test "$OS" = "windows"; then
                OUTPUT_BIN="${OUTPUT_BIN}.exe"
            else
                LINKFLAGS=" -linkmode external $LINKFLAGS"
            fi
            echo "Building binary for $OS/$ARCH..."
            GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build \
                  -ldflags="-X main.VERSION=$VERSION $LINKFLAGS" \
                  -o ${OUTPUT_BIN} ./
        done
    done
fi
