#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/rancher-dns .
docker build -t ${REPO}/rancher-dns:${TAG} .

echo Built ${REPO}/rancher-dns:${TAG}
